openapi: 3.0.0
info:
  title: jaoapi
  version: '1.0'
  description: |-
    jao Minecraft Server API Version 1

    Old documentation: https://jaoafa.github.io/api-docs_old/

    jao Minecraft Server API Terms of Service: https://api.jaoafa.com/tos

    ## Basic Infomation

    - BaseURL: `https://api.jaoafa.com/`
    - Available Version: `v1` (`https://api.jaoafa.com/v1/`)
    - バージョンを指定せずリクエストすることもできます。その場合、最新バージョンが選択されます。
    - GETリクエストにおいて、同一エンドポイントに対してのリクエストで同一フィールドを複数指定した場合、?で指定されたフィールドを優先して使用します。
      - `v1/users/X4Z?mcid=mine_book000`: mcid=`mine_book000`のデータを取得
      - `v1/users/X4Z?uuid=xxxxx`: uuid=`xxxxx`のデータを取得

    ## Rate Limits

    すべてのエンドポイントにおいて、リクエスト先エンドポイントに関係なく同一IPアドレスからの10秒以内に2回以上のリクエストを規制します。
    リクエストが規制された場合、レスポンスヘッダーのx-ratelimit-resetに制限が解除されるUNIXTimeが記載されます。

    `/club/token`で取得されたトークンを`usertoken`パラメーターに設定してリクエストした場合、トークンが有効であればレートリミット制限が無効化されます。
    また、Google reCAPTCHAでの認証トークンを`raterecaptcha`パラメーターに設定してリクエストした場合でも、トークンが有効であればレートリミット制限が無効化されます。

    ## Other Restriction

    開発部は開発部の判断により特定IPからのアクセスを禁止、またはレートリミットを無効化する処置を行うことができます。
  license:
    name: jaoLicense
    url: 'https://github.com/jaoafa/jao-Minecraft-Server/blob/master/jaoLICENSE.md'
  contact:
    url: 'https://jaoafa.com/contact'
    name: Contact
    email: info@jaoafa.com
  termsOfService: 'https://api.jaoafa.com/tos'
servers:
  - url: 'https://api.jaoafa.com/v1'
    description: API Server
components:
  schemas:
    User:
      title: User
      type: object
      x-examples: {}
      description: jao Minecraft Server Minecraft サービスにログインしたことのある利用者の情報オブジェクト
      properties:
        mcid:
          type: string
          example: X4Z
          pattern: '^[A-Za-z0-9_]+$'
          minLength: 3
          maxLength: 16
          description: Minecraft ID
        uuid:
          type: string
          format: uuid
          example: 5799296a-d1ec-4252-93bd-440bb9caa65c
          pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$'
          minLength: 36
          maxLength: 36
          description: Minecraft UUID (with hyphen)
        discordid:
          type: string
          example: '206692134991036416'
          pattern: '^[0-9]+$'
          description: Discord ID
        permission:
          type: string
          enum:
            - admin
            - moderator
            - regular
            - verified
            - default
          example: admin
          description: Permission Group
        lastlogin:
          type: string
          example: '2020-04-12 09:03:58'
          description: Last login time
      required:
        - mcid
        - uuid
        - discordid
        - permission
        - lastlogin
      x-tags:
        - Users
    MCBans-User:
      description: MCBansユーザデータオブジェクト
      type: object
      title: MCBans-User
      properties:
        uuid:
          type: string
          minLength: 36
          example: 5799296a-d1ec-4252-93bd-440bb9caa65c
          pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$'
          maxLength: 36
        global:
          type: integer
          minimum: 0
          example: 0
        reputation:
          type: integer
          maximum: 10
          exclusiveMaximum: false
        global_ids:
          type: array
          uniqueItems: true
          items:
            type: integer
        local:
          type: number
          minimum: 0
        local_ids:
          type: array
          uniqueItems: true
          items:
            type: integer
        updated_at:
          type: string
          pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'
          example: '2020-01-01 00:00:00'
      required:
        - uuid
        - global
        - reputation
        - global_ids
        - local
        - local_ids
        - updated_at
      x-examples:
        'example: X4Z (5799296a-d1ec-4252-93bd-440bb9caa65)':
          uuid: 5799296a-d1ec-4252-93bd-440bb9caa65c
          global: 0
          reputation: 10
          global_ids: []
          local: 0
          local_ids: []
          updated_at: '2020-05-05 04:16:50'
      x-tags:
        - User-MCBans
    Basic-Response:
      type: object
      title: Basic-Response
      description: |-
        基本レスポンス

        基本レスポンスは、すべての API のレスポンスに必ず組み込まれます。
        以下基本レスポンスに追加して各エンドポイント独自のレスポンスがマージされて返却されます。

        エラーの場合(`status`が`false`の場合)、エンドポイントによっては`message`・`message_ja`が返却されます。
      properties:
        status:
          type: boolean
          description: Response Status
        code:
          type: integer
          example: 200
          description: HTTP Status Code
        version:
          type: string
          minLength: 40
          maxLength: 40
          pattern: '^[a-z0-9]+$'
          description: API Minor Version (GitHub Commit ID)
        message:
          type: string
          description: status = falseの場合、エラー理由(基本英語)
        message_ja:
          type: string
          description: status = falseの場合、エラー理由(日本語)
      required:
        - status
        - code
        - version
    MCBans-User-Ban:
      description: MCBans Banデータオブジェクト
      type: object
      title: MCBans-User-Ban
      x-examples:
        'example: X4Z (5799296a-d1ec-4252-93bd-440bb9caa65)':
          mcid: X4Z
          banned_by: X4Z
          reason: griefing
          server: play.jaoafa.com
          type: global
          lostrep: 1
          date: '2020-01-01 00:00:00'
          updated_at: '2020-01-01 00:00:00'
      properties:
        mcid:
          type: string
          minLength: 3
          pattern: '^[A-Za-z0-9_]+$'
          maxLength: 16
          example: X4Z
          description: Minecraft ID
        banned_by:
          type: string
          minLength: 3
          description: Minecraft ID of the user who executed Ban
          pattern: '^[A-Za-z0-9_]+$'
          example: X4Z
          maxLength: 16
        reason:
          type: string
          minLength: 1
          description: Ban Reason
          example: griefing
        server:
          type: string
          minLength: 1
          example: play.jaoafa.com
          description: Server on which Ban was run
        type:
          type: string
          minLength: 1
          description: Ban Type
        lostrep:
          type: number
          example: 1
          description: Lost Reputation
        date:
          type: string
          minLength: 1
          description: Ban datetime (JST)
          example: '2020-01-01 00:00:00'
          pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'
        updated_at:
          type: string
          minLength: 1
          description: Data update datetime (JST)
          pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'
          example: '2020-01-01 00:00:00'
      required:
        - mcid
        - banned_by
        - reason
        - server
        - type
        - lostrep
        - date
        - updated_at
      x-tags:
        - User-MCBans
    DataShareItem:
      title: DataShareItem
      type: object
      x-tags:
        - Club
      description: |-
        DataShareにアップロードされているアイテムのオブジェクト

        hash, bytes, last_modifiedはConoHaのAPIから取得。それ以外はjaoMainデータベースより

        参考: https://www.conoha.jp/docs/swift-show_container_details_and_list_objects.php
      properties:
        id:
          type: integer
          description: DataShareItem ID
          example: 1
          minimum: 1
        name:
          type: string
          description: File name (DBデータ)
          example: jaoafa.zip
        hash:
          type: string
          description: File hash
          example: 1276481102f218c981e0324180bafd9f
          minLength: 32
        bytes:
          type: integer
          description: File size(bytes)
          example: 10240
        last_modified:
          type: string
          description: File last modified
          example: '2015-05-07T08:24:16.697500'
        download_count:
          type: integer
          minimum: 0
          example: 1
          description: File download Count
        uploader:
          type: object
          required:
            - mcid
            - uuid
          description: Item Uploader data
          properties:
            mcid:
              type: string
              example: X4Z
              pattern: '^[A-Za-z0-9_]+$'
              minLength: 3
              maxLength: 16
              description: Item Uploader Minecraft ID
            uuid:
              type: string
              example: 5799296a-d1ec-4252-93bd-440bb9caa65c
              pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$'
              minLength: 36
              maxLength: 36
              format: uuid
              description: Item Uploader Minecraft UUID
      required:
        - id
        - name
        - hash
        - bytes
        - last_modified
        - download_count
        - uploader
  securitySchemes: {}
paths:
  /users:
    get:
      summary: Get User
      tags:
        - Users
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  status:
                    type: boolean
                    description: Response status
                  code:
                    type: integer
                    example: 200
                    description: HTTP Status code
                  version:
                    type: string
                    minLength: 1
                    description: API Minor Version (GitHub Commit ID)
                  data:
                    $ref: '#/components/schemas/User'
                required:
                  - status
                  - code
                  - version
                  - data
              examples:
                'example: ?mcid=X4Z':
                  value:
                    status: true
                    code: 200
                    version: 91945bb4463e9b2ca0d1e82a0224f16cf1003fa3
                    data:
                      mcid: X4Z
                      uuid: 5799296a-d1ec-4252-93bd-440bb9caa65c
                      permission: admin
                      lastlogin: '2020-10-18 17:22:39'
                      discordid: '206692134991036416'
                      voteCount: 1431
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Basic-Response'
              examples:
                example:
                  value:
                    status: false
                    code: 404
                    version: 91945bb4463e9b2ca0d1e82a0224f16cf1003fa3
                    message: No user found with that Minecraft ID.
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Basic-Response'
      operationId: get-users
      description: |-
        ユーザオブジェクトを返します。
        このエンドポイントで返されるMinecraft IDは最新でない可能性があることに注意してください。jao Minecraft Serverの最終ログインの情報から取得されます。

        パラメータはすべてOptionalですが、いずれかかのパラメータは必須です。
      parameters:
        - schema:
            type: string
          in: query
          name: mcid
          description: Minecraft ID
        - schema:
            type: string
            pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$'
            example: 5799296a-d1ec-4252-93bd-440bb9caa65c
          in: query
          name: uuid
          description: Minecraft UUID
        - schema:
            type: string
          in: query
          name: discordid
          description: Discord ID
  '/users/{any}':
    parameters:
      - schema:
          type: string
          example: X4Z
          minLength: 1
        name: any
        in: path
        required: true
        description: 'Minecraft ID, Minecraft UUID, DiscordIDのいずれか'
    get:
      summary: Get User
      tags:
        - Users
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  status:
                    type: boolean
                    description: Response status
                  code:
                    type: integer
                    example: 200
                    description: HTTP Status code
                  version:
                    type: string
                    minLength: 1
                    description: API Minor Version (GitHub Commit ID)
                  data:
                    $ref: '#/components/schemas/User'
                required:
                  - status
                  - code
                  - version
                  - data
              examples:
                'example: X4Z':
                  value:
                    status: true
                    code: 200
                    version: 91945bb4463e9b2ca0d1e82a0224f16cf1003fa3
                    data:
                      mcid: X4Z
                      uuid: 5799296a-d1ec-4252-93bd-440bb9caa65c
                      permission: admin
                      lastlogin: '2020-10-18 17:22:39'
                      discordid: '206692134991036416'
                      voteCount: 1431
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Basic-Response'
              examples:
                example:
                  value:
                    status: false
                    code: 404
                    version: 91945bb4463e9b2ca0d1e82a0224f16cf1003fa3
                    message: No user found with that Minecraft ID.
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Basic-Response'
      operationId: get-users-any
      description: |-
        ユーザオブジェクトを返します。
        このエンドポイントで返されるMinecraft IDは最新でない可能性があることに注意してください。jao Minecraft Serverの最終ログインの情報から取得されます。

        OpenAPIの仕様上、異なるパスパラメータのエンドポイントを異なるものとして扱うことができないため、本API仕様書では以下のエンドポイントを同一の`/users/{any}`として記述します。どのエンドポイントを使用しても返却されるレスポンスは変わりません。
        - GET `/users/{minecraft.id}`
        - GET `/users/{minecraft.uuid}`
        - GET `/users/{discord.id}`
      parameters: []
  /users/mcbans:
    get:
      summary: Get MCBans User Data
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: Response Status
                  code:
                    type: integer
                    description: HTTP Status Code
                    example: 200
                  version:
                    type: string
                    description: API Minor Version (GitHub Commit ID)
                    minLength: 40
                    maxLength: 40
                    pattern: '^[a-z0-9]+$'
                  data:
                    $ref: '#/components/schemas/MCBans-User'
                required:
                  - status
                  - code
                  - version
                  - data
              examples: {}
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Basic-Response'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Basic-Response'
      operationId: get-users-mcbans
      description: MCBansユーザデータオブジェクトを返します。
      parameters:
        - schema:
            type: string
            pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$'
            minLength: 36
            maxLength: 36
            example: 5799296a-d1ec-4252-93bd-440bb9caa65c
          in: query
          name: uuid
          description: Minecraft UUID (with hyphen)
          required: true
      tags:
        - User-MCBans
  '/users/mcbans/ban/{banid}':
    parameters:
      - schema:
          type: integer
          example: 1
          pattern: '^[0-9]+$'
          minimum: 1
        name: banid
        in: path
        required: true
        description: MCBans BanID
    get:
      summary: Get MCBans Ban Data
      tags:
        - User-MCBans
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  status:
                    type: boolean
                    description: Response Status
                  code:
                    type: integer
                    description: HTTP Status Code
                  version:
                    type: string
                    minLength: 1
                    description: API Minor Version (GitHub Commit ID)
                  data:
                    $ref: '#/components/schemas/MCBans-User-Ban'
                required:
                  - status
                  - code
                  - version
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Basic-Response'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Basic-Response'
      operationId: get-users-mcbans-ban-banid
      description: MCBans Banデータオブジェクトを返します。
  /club/datashare/search:
    get:
      summary: Search DataShare Item(s)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  status:
                    type: boolean
                    description: Response status
                  code:
                    type: integer
                    example: 200
                    description: HTTP Status code
                  version:
                    type: string
                    minLength: 1
                    description: API Minor Version (GitHub Commit ID)
                  data:
                    type: array
                    description: Array of DataShareItem
                    minItems: 0
                    items:
                      $ref: '#/components/schemas/DataShareItem'
                required:
                  - status
                  - code
                  - version
                  - data
      operationId: get-club-datashare-search
      description: |-
        パラメータに応じて検索し、DataShareItemオブジェクトを配列で返します。

        パラメータを指定しないとすべてのDataShareItemオブジェクトを返します。複数のパラメータを指定した場合、`id`, `uuid`, `content_type`の順で検索します(それ以外のパラメータは無視されます)。

        `recaptcha`もしくは`usertoken`のどちらかが必須です。
      parameters:
        - schema:
            type: string
            example: 5799296a-d1ec-4252-93bd-440bb9caa65c
            pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$'
            minLength: 36
            maxLength: 36
            format: uuid
          in: query
          name: uuid
          description: Upload User UUID
        - schema:
            type: string
            example: application/octet-stream
            minLength: 1
          in: query
          name: content_type
          description: Content Type
        - schema:
            type: string
          in: query
          name: recaptcha
          description: Google reCAPTCHA
        - schema:
            type: string
          in: query
          name: usertoken
          description: clubjaoafa User Token
      tags:
        - Club-DataShare
    parameters: []
  '/club/datashare/{datashareitemid}':
    get:
      summary: Get DataShare Item
      tags:
        - Club-DataShare
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                description: File binary
                format: binary
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Basic-Response'
      operationId: get-club-datashare
      description: DataShareのアイテムを取得(ダウンロード)します。
      parameters: []
    delete:
      summary: Delete DataShare Item
      tags:
        - Club-DataShare
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Basic-Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Basic-Response'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  status:
                    type: boolean
                    description: Response status
                  code:
                    type: integer
                    example: 200
                    description: HTTP Status code
                  version:
                    type: string
                    minLength: 1
                    description: API Minor Version (GitHub Commit ID)
                required:
                  - status
                  - code
                  - version
      operationId: delete-club-datashare
      description: |
        DataShareのアイテムを削除します。
    parameters:
      - schema:
          type: integer
        name: datashareitemid
        in: path
        description: DataShareItem ID
        required: true
  /club/datashare:
    post:
      summary: Upload DataShare Item
      tags:
        - Club-DataShare
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Basic-Response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Basic-Response'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Basic-Response'
      operationId: post-club-datashare
      description: |-
        DataShareにアイテムをアップロードします。

        - アップロードできるファイルのファイルサイズは100MBまでです。
        - ConoHaオブジェクトストレージにアップロードされるファイルのファイル名は次のように書き換えられます: `<UUID>_<DataShareItemID>.<EXT>`
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                  description: Item name
                  example: jao鯖リソースパック
                description:
                  type: string
                  description: Item description
                  minLength: 0
                  example: jao Minecraft Serverの非公式リソースパックです。起動画面と絵画が変更されます。
                file:
                  type: string
                  format: binary
                  description: Upload file
                usertoken:
                  type: string
                  pattern: '^[a-z0-9]+$'
                  minLength: 32
                  maxLength: 32
                  example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                  description: clubjaoafa User Token
              required:
                - name
                - description
                - file
                - usertoken
tags:
  - name: Users
  - name: User-MCBans
  - name: Club
  - name: Club-DataShare
security: []
